# Generated by Django 4.1.7 on 2023-05-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medray', '0004_remove_info_last_name_info_customertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='CustomerType',
            field=models.CharField(max_length=50),
        ),
    ]
