# Generated by Django 4.1.7 on 2023-05-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medray', '0005_alter_info_customertype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='info',
            new_name='Customer_information',
        ),
    ]
