# Generated by Django 4.1.7 on 2023-05-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medray', '0009_display_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display_video',
            name='paste_link',
            field=models.CharField(max_length=200),
        ),
    ]
