# Generated by Django 4.1.7 on 2023-05-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medray', '0010_alter_display_video_paste_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='display_video',
            old_name='paste_link',
            new_name='link_1',
        ),
        migrations.AddField(
            model_name='display_video',
            name='Link_2',
            field=models.CharField(default='www.youtube.com', max_length=200),
        ),
    ]
