# Generated by Django 4.1.7 on 2023-05-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medray', '0011_rename_paste_link_display_video_link_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display_video',
            name='Link_2',
            field=models.CharField(max_length=200),
        ),
    ]
