# Generated by Django 4.1.7 on 2023-05-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medray', '0012_alter_display_video_link_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='display_video',
            old_name='Link_2',
            new_name='link_2',
        ),
    ]
