# Generated by Django 4.1.7 on 2023-05-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medray', '0013_rename_link_2_display_video_link_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_1', models.CharField(max_length=15)),
                ('description_1', models.TextField(max_length=60)),
                ('name_2', models.CharField(max_length=15)),
                ('description_2', models.TextField(max_length=60)),
            ],
        ),
    ]
