# Generated by Django 4.1.7 on 2023-05-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medray', '0015_alter_testimonials_description_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='description_1',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='description_2',
            field=models.TextField(max_length=300),
        ),
    ]
