# Generated by Django 4.1.7 on 2023-05-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medray', '0016_alter_testimonials_description_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Shipping_Address', models.CharField(max_length=50)),
                ('Pincode', models.CharField(max_length=6)),
                ('Mobile_Number', models.CharField(max_length=10)),
                ('Billing_to', models.CharField(max_length=40)),
                ('Billing_Address', models.CharField(max_length=50)),
                ('Product_Required', models.IntegerField(editable=False)),
            ],
        ),
    ]
