# Generated by Django 4.1.7 on 2023-05-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medray', '0017_buyinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyinfo',
            name='Product_Required',
            field=models.IntegerField(),
        ),
    ]
