# Generated by Django 4.1.7 on 2023-05-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medray', '0018_alter_buyinfo_product_required'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='buyinfo',
            new_name='Customer_order',
        ),
    ]
