# Generated by Django 4.1.7 on 2023-06-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medray', '0019_rename_buyinfo_customer_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ref_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Referral_Code', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
