# Generated by Django 4.1.7 on 2023-06-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medray', '0020_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='refcode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
