# Generated by Django 4.1.7 on 2023-06-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medray', '0021_customer_order_refcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='Price',
            field=models.IntegerField(default=83),
        ),
    ]
