# Generated by Django 4.1.7 on 2023-06-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medray', '0023_alter_customer_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ref_code',
            name='Amount_reduction',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='ref_code',
            name='Referral_Code',
            field=models.CharField(max_length=10),
        ),
    ]
