# Generated by Django 4.1.7 on 2023-06-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medray', '0024_ref_code_amount_reduction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=30)),
                ('Product_Amount', models.IntegerField(default='0')),
            ],
        ),
    ]
